### ISSUE TITLE
Building with parcel fails

### ISSUE THREAD

**Issue by puka-tchou** [brianvoe/slim-select#250]
**Describe the bug**
Building the project with `parcel@2.0.0-beta.1` fails with this error: `Error: Unknown version 85 of edge`

Full error log:

```
🚨 Build failed.
Error: Unknown version 85 of edge
BrowserslistError: Unknown version 85 of edge
    at Function.select (/builds/gaspacchio/back-to-the-future/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:1101:17)
    at /builds/gaspacchio/back-to-the-future/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (/builds/gaspacchio/back-to-the-future/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:318:18)
    at browserslist (/builds/gaspacchio/back-to-the-future/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:443:21)
    at getTargets (/builds/gaspacchio/back-to-the-future/node_modules/@babel/helper-compilation-targets/lib/index.js:204:48)
    at /builds/gaspacchio/back-to-the-future/node_modules/@babel/preset-env/lib/index.js:258:57
    at /builds/gaspacchio/back-to-the-future/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at getNeededPlugins (/builds/gaspacchio/back-to-the-future/node_modules/@parcel/transformer-babel/lib/env.js:47:33)
    at shouldCompileFurther (/builds/gaspacchio/back-to-the-future/node_modules/@parcel/transformer-babel/lib/env.js:55:31)
error Command failed with exit code 1.
```

You can see the full build here: https://gitlab.com/gaspacchio/back-to-the-future/-/jobs/911836491#L86

**Workaround**

Removing the `.browserslistrc` from your source seems to resolve the issue. Maybe there's an issue with it, I'll try to find it.

Running `npx browserlist` in your source folder resolves to:

```
and_chr 87         
and_ff 83          
and_qq 10.4        
and_uc 12.12       
android 81         
baidu 7.12         
bb 10              
bb 7               
chrome 87          
chrome 86          
edge 87            
edge 86            
firefox 83         
firefox 82         
ie 11              
ie 10              
ie_mob 11          
ie_mob 10          
ios_saf 14.0-14.2  
ios_saf 13.4-13.7  
ios_saf 12.2-12.4  
kaios 2.5          
op_mini all        
op_mob 59          
op_mob 12.1        
opera 72           
opera 71           
safari 14          
safari 13.1        
samsung 13.0       
samsung 12.0 
```

as you can see, `edge 85` is not in this list, so maybe there's a problem with `browserslist` itself or `babel`.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
