### ISSUE TITLE
Deselect with placeholder fails using vue component

### ISSUE THREAD

**Issue by pko734** [brianvoe/slim-select#458]
**Describe the bug**

```
            <slim-select select id="song_type" name="type" v-model="type" :settings="settings">
                <option data-placeholder="true"></option>
                <option value="covers">Covers</option>
                <option value="originals">Originals</option>
            </slim-select>

          settings: {
                   showSearch: false,
                   placeholderText: 'Select a type...',
                   allowDeselect: true
          }

```
When deselecting, this javascript error is thrown, and the bound v-model object doesn't get updated.

```
slimselectvue.es.js:1822 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at config.events.afterChange (slimselectvue.es.js:1822:1)
    at later (slimselectvue.es.js:36:1)

```

**Comment by brianvoe** [comment]
Ill see if i can figure out a way to implement the vue component better. Thanks for pointing this one out

**Comment by brianvoe** [comment]
I figured it out. Will go out in the next release
